##### Remove #####

#Combiner
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:3>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:4>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:5>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:11>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:12>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:19>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:20>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:21>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:23>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:24>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:25>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:31>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:32>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:33>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:48>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:44>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:46>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:45>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:44>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:43>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:42>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:41>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:40>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:39>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:38>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:37>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:36>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:35>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:34>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:49>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:50>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:51>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:52>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:53>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:54>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:55>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:56>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:57>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:58>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:59>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:60>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:61>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:62>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:63>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:64>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:65>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:66>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:67>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:68>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:69>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:70>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:71>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:72>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:73>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:74>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:75>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:76>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:77>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:78>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:79>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:80>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:81>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:82>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:83>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:84>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:85>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:86>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:87>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:88>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:89>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:90>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:91>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:92>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:93>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:94>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:95>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:96>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:97>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:98>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:99>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:100>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:101>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:102>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:103>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:104>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:105>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:106>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:107>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:108>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:109>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:110>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:111>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:112>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:113>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:114>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:115>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:116>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:117>);
mods.alchemistry.Combiner.removeRecipe(<alchemistry:ingot:118>);

#Disolver
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:3>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:4>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:5>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:11>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:12>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:19>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:20>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:21>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:23>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:24>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:25>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:31>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:32>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:33>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:48>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:44>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:46>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:45>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:44>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:43>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:42>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:41>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:40>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:39>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:38>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:37>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:36>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:35>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:34>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:49>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:50>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:51>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:52>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:53>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:54>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:55>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:56>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:57>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:58>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:59>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:60>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:61>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:62>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:63>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:64>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:65>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:66>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:67>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:68>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:69>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:70>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:71>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:72>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:73>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:74>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:75>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:76>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:77>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:78>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:79>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:80>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:81>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:82>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:83>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:84>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:85>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:86>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:87>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:88>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:89>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:90>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:91>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:92>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:93>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:94>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:95>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:96>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:97>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:98>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:99>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:100>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:101>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:102>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:103>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:104>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:105>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:106>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:107>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:108>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:109>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:110>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:111>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:112>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:113>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:114>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:115>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:116>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:117>);
mods.alchemistry.Dissolver.removeRecipe(<alchemistry:ingot:118>);

#Liquifier
mods.alchemistry.Liquifier.removeAllRecipes();

#Atomizer
mods.alchemistry.Atomizer.removeAllRecipes();

#Electrolyser
mods.alchemistry.Electrolyzer.removeRecipe(<liquid:water>*125,<alchemistry:compound:13>);

#Crafting
recipes.remove(<alchemistry:wet_sand>);
recipes.remove(<alchemistry:chemical_combiner>);
recipes.remove(<alchemistry:chemical_dissolver>);
recipes.remove(<alchemistry:fusion_casing>);
recipes.remove(<alchemistry:fusion_controller>);
recipes.remove(<alchemistry:fission_core>);
recipes.remove(<alchemistry:fission_casing>);
recipes.remove(<alchemistry:fission_controller>);


##### Add #####

#Compound
#AddMethanol CH3(OH)
mods.alchemistry.Util.createCompound(1000, "methanol", 100, 90, 120,[["carbon", 1],["hydrogen", 3],["hydroxide", 1]]);

#Electrolyser
mods.alchemistry.Electrolyzer.addRecipe(<liquid:water>*125,<alchemistry:compound:13>,10,<alchemistry:element:1>*2,<alchemistry:element:8>,null,0,null,0);

#Liquifier
mods.alchemistry.Liquifier.addRecipe(<liquid:bio.ethanol>*125,<alchemistry:compound:26>*2);
mods.alchemistry.Liquifier.addRecipe(<liquid:water>*125,<alchemistry:compound:7>*2);
mods.alchemistry.Liquifier.addRecipe(<liquid:methanol>*125,<alchemistry:compound:1000>*2);
mods.alchemistry.Liquifier.addRecipe(<liquid:if.protein>*80,<alchemistry:compound:3>*2);
mods.alchemistry.Liquifier.addRecipe(<liquid:chlorine>*125,<alchemistry:element:17>*2);
mods.alchemistry.Liquifier.addRecipe(<liquid:hydrogen>*125,<alchemistry:element:1>*2);
mods.alchemistry.Liquifier.addRecipe(<liquid:oxygen>*125,<alchemistry:element:8>*2);
mods.alchemistry.Liquifier.addRecipe(<liquid:nitrogen>*125,<alchemistry:element:7>*2);

#Atomizer
mods.alchemistry.Atomizer.addRecipe(<alchemistry:compound:26>*2,<liquid:bio.ethanol>*125);
mods.alchemistry.Atomizer.addRecipe(<alchemistry:compound:1000>*2,<liquid:methanol>*125);
mods.alchemistry.Atomizer.addRecipe(<alchemistry:compound:9>*3,<liquid:if.protein>*80);
mods.alchemistry.Atomizer.addRecipe(<alchemistry:element:17>*2,<liquid:chlorine>*125);
mods.alchemistry.Atomizer.addRecipe(<alchemistry:element:1>*2,<liquid:hydrogen>*125);
mods.alchemistry.Atomizer.addRecipe(<alchemistry:element:8>*2,<liquid:oxygen>*125);
mods.alchemistry.Atomizer.addRecipe(<alchemistry:element:7>*2,<liquid:nitrogen>*125);


#Crafting
recipes.addShaped(<alchemistry:chemical_combiner>,[[<immersiveintelligence:sheetmetal>,<ore:ingotYellorium>,<immersiveintelligence:sheetmetal>],[<ore:ingotTungsten>,<immersiveengineering:storage:8>,<ore:ingotTungsten>],[<ore:ingotTungsten>,<immersiveengineering:metal_device0:2>,<ore:ingotTungsten>]]);
recipes.addShaped(<alchemistry:chemical_combiner>,[[<immersiveintelligence:sheetmetal>,<ore:ingotYellorium>,<immersiveintelligence:sheetmetal>],[<ore:ingotTitanium>,<immersiveengineering:storage:8>,<ore:ingotTitanium>],[<ore:ingotTitanium>,<immersiveengineering:metal_device0:2>,<ore:ingotTitanium>]]);
recipes.addShaped(<alchemistry:chemical_dissolver>,[[<immersiveintelligence:sheetmetal>,<minecraft:diamond>,<immersiveintelligence:sheetmetal>],[<ore:ingotTungsten>,<immersiveengineering:storage:8>,<ore:ingotTungsten>],[<ore:ingotTungsten>,<immersiveengineering:metal_device0:2>,<ore:ingotTungsten>]]);
recipes.addShaped(<alchemistry:chemical_dissolver>,[[<immersiveintelligence:sheetmetal>,<minecraft:diamond>,<immersiveintelligence:sheetmetal>],[<ore:ingotTitanium>,<immersiveengineering:storage:8>,<ore:ingotTitanium>],[<ore:ingotTitanium>,<immersiveengineering:metal_device0:2>,<ore:ingotTitanium>]]);
recipes.addShaped(<alchemistry:fusion_casing>,[[<ore:ingotTungsten>,<ore:ingotTitanium>,<ore:ingotTungsten>],[<ore:ingotTitanium>,<ore:ingotYellorium>,<ore:ingotTitanium>],[<ore:ingotTungsten>,<ore:ingotTitanium>,<ore:ingotTungsten>]]);
recipes.addShaped(<alchemistry:fission_casing>,[[<ore:ingotTungsten>,<ore:ingotTitanium>,<ore:ingotTungsten>],[<ore:ingotTitanium>,<minecraft:blaze_powder>,<ore:ingotTitanium>],[<ore:ingotTungsten>,<ore:ingotTitanium>,<ore:ingotTungsten>]]);
recipes.addShaped(<alchemistry:fusion_controller>,[[<ore:ingotSteel>,<alchemistry:fusion_casing>,<ore:ingotSteel>],[<ore:blockGlass>,<minecraft:ender_eye>,<ore:ingotPlatinum>],[<ore:ingotSteel>,<alchemistry:fusion_casing>,<ore:ingotSteel>]]);
recipes.addShaped(<alchemistry:fission_controller>,[[<ore:ingotSteel>,<alchemistry:fission_casing>,<ore:ingotSteel>],[<ore:blockGlass>,<minecraft:ender_eye>,<ore:ingotPlatinum>],[<ore:ingotSteel>,<alchemistry:fission_casing>,<ore:ingotSteel>]]);
recipes.addShaped(<alchemistry:fission_core>,[[<ore:ingotPlatinum>,<ore:ingotYellorium>,<ore:ingotPlatinum>],[<ore:ingotPlatinum>,<ore:ingotYellorium>,<ore:ingotPlatinum>],[<ore:ingotPlatinum>,<ore:ingotYellorium>,<ore:ingotPlatinum>]]);