import mods.industrialforegoing.ProteinReactor;

##### Ore Dictionary #####

<ore:ingotYellorium>.add(<immersive_energy:stick_thorium>);
<ore:ingotYellorium>.add(<immersive_energy:stick_uranium>);
<ore:ingotGraphite>.add(<immersiveengineering:material:19>);
<ore:ingotGraphite>.remove(<bigreactors:ingotgraphite>);
<ore:dustGraphite>.remove(<bigreactors:dustgraphite>);

<ore:dustGraphite>.remove(<bigreactors:ingotgraphite>);
<ore:dustGraphite>.remove(<bigreactors:blockgraphite>);
##### Remove #####

#Immersive
mods.immersiveengineering.Fermenter.removeByInput(<minecraft:reeds>);
mods.immersiveengineering.Fermenter.removeByInput(<minecraft:apple>);
mods.immersiveengineering.Fermenter.removeByInput(<minecraft:melon>);
mods.immersiveengineering.Fermenter.removeByInput(<minecraft:potato>);

mods.immersiveengineering.Refinery.removeRecipe(<liquid:biodiesel>);

mods.immersiveengineering.Squeezer.removeFluidRecipe(<liquid:plantoil>);

#Steam
mods.immersivetechnology.SolarTower.removeRecipe(<liquid:water>);
mods.immersivetechnology.SolarTower.removeRecipe(<liquid:distwater>);

mods.immersivetechnology.Boiler.removeRecipe(<liquid:water>);
mods.immersivetechnology.Boiler.removeRecipe(<liquid:distwater>);

mods.immersivetechnology.HeatExchanger.removeRecipe(<liquid:water>,<liquid:fluegas>);
mods.immersivetechnology.HeatExchanger.removeRecipe(<liquid:distwater>,<liquid:fluegas>);

mods.immersivetechnology.Boiler.removeFuel(<liquid:fluegas>);
mods.immersivetechnology.Boiler.removeFuel(<liquid:diesel>);
mods.immersivetechnology.Boiler.removeFuel(<liquid:biodiesel>);
mods.immersivetechnology.Boiler.removeFuel(<liquid:gasoline>);

mods.immersivetechnology.SteamTurbine.removeFuel(<liquid:steam>);

mods.immersivetechnology.GasTurbine.removeFuel(<liquid:biodiesel>);
mods.immersivetechnology.GasTurbine.removeFuel(<liquid:diesel>);
mods.immersivetechnology.GasTurbine.removeFuel(<liquid:gasoline>);
mods.immersivetechnology.GasTurbine.removeFuel(<liquid:methanol>);
mods.immersivetechnology.GasTurbine.removeFuel(<liquid:fluegas>);

mods.immersivetechnology.CoolingTower.removeRecipe(<liquid:exhauststeam>, <liquid:water>);
mods.immersivetechnology.CoolingTower.removeRecipe(<liquid:exhauststeam>, <liquid:distwater>);

mods.immersivetechnology.Distiller.removeRecipe(<liquid:water>);

#Reactor

furnace.remove(<bigreactors:ingotgraphite>);
recipes.remove(<bigreactors:reactorcasing>);
recipes.remove(<immersiveposts:metal_rods:7>);
recipes.remove(<bigreactors:reactorcasingcores>);
recipes.remove(<bigreactors:turbinehousing>);
recipes.remove(<bigreactors:turbinehousingcores>);
recipes.remove(<bigreactors:turbinerotorblade>);


mods.immersiveengineering.Crusher.removeRecipe(<bigreactors:dustgraphite>);

##### Add #####

#Immersive

mods.immersiveengineering.Refinery.addRecipe(<liquid:biodiesel>*22,<liquid:seed.oil>*11,<liquid:bio.ethanol>*11,400);

#Crafting
recipes.addShaped(<immersiveengineering:toolupgrade:1>,[[<liquid:seed.oil>*1000,<minecraft:iron_ingot>,null],[<minecraft:iron_ingot>,<liquid:seed.oil>*1000,<minecraft:iron_ingot>],[null,<minecraft:iron_ingot>,<immersiveengineering:material:8>]]);

#Steam

mods.immersivetechnology.Boiler.addRecipe(<liquid:steam>*360,<liquid:water>*180,1);
mods.immersivetechnology.Boiler.addRecipe(<liquid:steam>*360,<liquid:distwater>*120,1);
mods.immersivetechnology.SolarTower.addRecipe(<liquid:steam>*180,<liquid:water>*90,1);
mods.immersivetechnology.SolarTower.addRecipe(<liquid:steam>*180,<liquid:distwater>*60,1);
mods.immersivetechnology.HeatExchanger.addRecipe(<liquid:steam>*720,null,<liquid:water>*360,<liquid:fluegas>*5,128,1);
mods.immersivetechnology.HeatExchanger.addRecipe(<liquid:steam>*720,null,<liquid:distwater>*240,<liquid:fluegas>*5,128,1);

mods.immersivetechnology.Boiler.addFuel(<liquid:diesel>* 5, 3, 10);
mods.immersivetechnology.Boiler.addFuel(<liquid:biodiesel>* 5, 3, 10);
mods.immersivetechnology.Boiler.addFuel(<liquid:gasoline>* 5, 3, 15);
mods.immersivetechnology.Boiler.addFuel(<liquid:bio.ethanol>* 10, 3, 5);
mods.immersivetechnology.Boiler.addFuel(<liquid:lava>* 10, 1, 30);

mods.immersivetechnology.Boiler.addFuel(<liquid:fluegas>* 10, 1, 5);
mods.immersivetechnology.Boiler.addFuel(<liquid:methanol>* 10, 1, 5);
mods.immersivetechnology.Boiler.addFuel(<liquid:hydrogen>* 20, 1, 5);

mods.immersivetechnology.SteamTurbine.addFuel(<liquid:exhauststeam> * 720, <liquid:steam> * 720, 1);

mods.immersivetechnology.GasTurbine.addFuel(<liquid:fluegas>*100,<liquid:biodiesel>*100,60);
mods.immersivetechnology.GasTurbine.addFuel(<liquid:fluegas>*100,<liquid:diesel>*75,60);
mods.immersivetechnology.GasTurbine.addFuel(<liquid:fluegas>*100,<liquid:gasoline>*50,60);
mods.immersivetechnology.GasTurbine.addFuel(<liquid:fluegas>*100,<liquid:methanol>*200,60);
mods.immersivetechnology.GasTurbine.addFuel(<liquid:fluegas>*100,<liquid:bio.ethanol>*150,60);

mods.immersivetechnology.CoolingTower.addRecipe(<liquid:water> * 180, <liquid:water> * 180,<liquid:water> * 180, <liquid:exhauststeam> * 720, 1);
mods.immersivetechnology.CoolingTower.addRecipe(<liquid:distwater> * 120, <liquid:distwater> * 120, <liquid:distwater> * 120, <liquid:exhauststeam> * 720, 1);

mods.immersivetechnology.Distiller.addRecipe(<liquid:distwater> * 960, <liquid:water> * 1000, <immersiveintelligence:material:19>, 128,1,0.05F);

mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale> * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider> * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine> * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine> * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine> * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:biomass> * 100, <minecraft:sugar>, 160,10,0.05F);

#Reactor

recipes.addShaped(<immersive_energy:stick_uranium>*2,[[<immersiveengineering:metal:5>],[<immersiveengineering:metal:5>]]);
recipes.addShaped(<immersive_energy:stick_uranium>*2,[[<immersiveengineering:metal:5>],[<immersiveengineering:metal:5>]]);
recipes.addShaped(<bigreactors:reactorcasing>*4,[[<ore:ingotTungsten>,<ore:ingotGraphite>,<ore:ingotTungsten>],[<ore:ingotGraphite>,<bigreactors:reactorcasingcores>,<ore:ingotGraphite>],[<ore:ingotTungsten>,<ore:ingotGraphite>,<ore:ingotTungsten>]]);
recipes.addShaped(<bigreactors:reactorcasing>*4,[[<ore:ingotTitanium>,<ore:ingotGraphite>,<ore:ingotTitanium>],[<ore:ingotGraphite>,<bigreactors:reactorcasingcores>,<ore:ingotGraphite>],[<ore:ingotTitanium>,<ore:ingotGraphite>,<ore:ingotTitanium>]]);
recipes.addShaped(<bigreactors:reactorcasingcores>,[[<immersiveengineering:material:2>,<ore:ingotGraphite>,<immersiveengineering:material:2>],[<minecraft:gold_ingot>,<minecraft:redstone>,<minecraft:gold_ingot>],[<immersiveengineering:material:2>,<ore:ingotGraphite>,<immersiveengineering:material:2>]]);

mods.immersiveengineering.Crusher.addRecipe(<immersiveengineering:material:18>, <immersiveengineering:material:19>, 2048);

recipes.addShapeless(<bigreactors:blockgraphite>,[<immersiveengineering:material:19>,<immersiveengineering:material:19>,<immersiveengineering:material:19>,<immersiveengineering:material:19>,<immersiveengineering:material:19>,<immersiveengineering:material:19>,<immersiveengineering:material:19>,<immersiveengineering:material:19>,<immersiveengineering:material:19>]);
recipes.addShapeless(<immersiveengineering:material:19>*9,[<bigreactors:blockgraphite>]);

#Juice to alk
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.01 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.02 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.03 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.04 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.05 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.06 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.07 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.08 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.09 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.10 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.11 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.12 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.13 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.14 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.15 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.16 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.17 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.18 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.19 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.20 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.21 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.22 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.23 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.24 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.25 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.26 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.27 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.28 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.29 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.30 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.31 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.32 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.33 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.34 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.35 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.36 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.37 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.38 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.39 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.40 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.41 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.42 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.43 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.44 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.45 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.46 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.47 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.48 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.49 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.50 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.51 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.52 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.53 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.54 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.55 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.56 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.57 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.58 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.59 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.60 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.61 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.62 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.63 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.64 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.65 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.66 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.67 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.68 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.69 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.70 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.71 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.72 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.73 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.74 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.75 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.76 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.77 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.78 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.79 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.80 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.81 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.82 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.83 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.84 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.85 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.86 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.87 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.88 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.89 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.90 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.91 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.92 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.93 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.94 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.95 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.96 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.97 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.98 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 0.99 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wildberrywine>.withTag({Quality: 1.00 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);

mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.01 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.02 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.03 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.04 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.05 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.06 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.07 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.08 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.09 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.10 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.11 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.12 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.13 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.14 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.15 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.16 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.17 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.18 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.19 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.20 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.21 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.22 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.23 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.24 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.25 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.26 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.27 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.28 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.29 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.30 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.31 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.32 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.33 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.34 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.35 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.36 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.37 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.38 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.39 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.40 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.41 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.42 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.43 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.44 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.45 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.46 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.47 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.48 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.49 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.50 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.51 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.52 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.53 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.54 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.55 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.56 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.57 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.58 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.59 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.60 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.61 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.62 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.63 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.64 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.65 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.66 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.67 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.68 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.69 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.70 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.71 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.72 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.73 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.74 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.75 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.76 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.77 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.78 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.79 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.80 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.81 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.82 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.83 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.84 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.85 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.86 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.87 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.88 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.89 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.90 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.91 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.92 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.93 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.94 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.95 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.96 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.97 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.98 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 0.99 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ale>.withTag({Quality: 1.00 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);

mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.01 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.02 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.03 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.04 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.05 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.06 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.07 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.08 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.09 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.10 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.11 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.12 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.13 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.14 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.15 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.16 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.17 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.18 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.19 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.20 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.21 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.22 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.23 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.24 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.25 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.26 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.27 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.28 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.29 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.30 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.31 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.32 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.33 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.34 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.35 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.36 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.37 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.38 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.39 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.40 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.41 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.42 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.43 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.44 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.45 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.46 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.47 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.48 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.49 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.50 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.51 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.52 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.53 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.54 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.55 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.56 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.57 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.58 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.59 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.60 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.61 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.62 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.63 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.64 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.65 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.66 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.67 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.68 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.69 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.70 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.71 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.72 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.73 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.74 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.75 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.76 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.77 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.78 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.79 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.80 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.81 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.82 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.83 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.84 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.85 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.86 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.87 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.88 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.89 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.90 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.91 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.92 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.93 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.94 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.95 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.96 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.97 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.98 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 0.99 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:cider>.withTag({Quality: 1.00 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);

mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.01 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.02 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.03 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.04 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.05 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.06 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.07 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.08 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.09 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.10 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.11 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.12 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.13 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.14 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.15 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.16 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.17 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.18 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.19 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.20 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.21 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.22 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.23 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.24 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.25 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.26 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.27 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.28 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.29 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.30 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.31 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.32 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.33 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.34 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.35 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.36 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.37 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.38 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.39 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.40 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.41 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.42 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.43 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.44 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.45 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.46 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.47 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.48 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.49 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.50 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.51 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.52 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.53 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.54 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.55 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.56 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.57 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.58 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.59 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.60 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.61 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.62 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.63 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.64 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.65 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.66 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.67 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.68 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.69 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.70 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.71 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.72 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.73 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.74 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.75 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.76 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.77 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.78 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.79 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.80 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.81 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.82 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.83 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.84 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.85 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.86 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.87 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.88 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.89 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.90 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.91 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.92 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.93 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.94 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.95 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.96 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.97 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.98 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 0.99 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:ironwine>.withTag({Quality: 1.00 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);

mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.01 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.02 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.03 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.04 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.05 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.06 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.07 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.08 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.09 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.10 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.11 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.12 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.13 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.14 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.15 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.16 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.17 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.18 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.19 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.20 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.21 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.22 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.23 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.24 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.25 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.26 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.27 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.28 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.29 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.30 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.31 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.32 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.33 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.34 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.35 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.36 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.37 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.38 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.39 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.40 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.41 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.42 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.43 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.44 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.45 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.46 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.47 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.48 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.49 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.50 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.51 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.52 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.53 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.54 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.55 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.56 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.57 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.58 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.59 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.60 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.61 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.62 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.63 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.64 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.65 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.66 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.67 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.68 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.69 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.70 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.71 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.72 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.73 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.74 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.75 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.76 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.77 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.78 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.79 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.80 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.81 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.82 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.83 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.84 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.85 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.86 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.87 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.88 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.89 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.90 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.91 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.92 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.93 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.94 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.95 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.96 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.97 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.98 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 0.99 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);
mods.immersivetechnology.Distiller.addRecipe(<liquid:bio.ethanol> * 30, <liquid:wine>.withTag({Quality: 1.00 as float}) * 100, <minecraft:sugar>, 160,10,0.05F);

#mods.jei.JEI.hideCategory("it.distiller");

#ProteinReactor

ProteinReactor.add(<alchemistry:compound:9>*3);

#Forestry Engin Tweaks
mods.forestry.engine.biogas.addRecipe(<liquid:bio.ethanol>, 65, 2500, 1);
mods.forestry.engine.peat.addRecipe(<minecraft:coal:1>, 15, 2000);
mods.forestry.engine.peat.addRecipe(<minecraft:coal:0>, 25, 2000);
mods.forestry.engine.peat.addRecipe(<minecraft:coal_block>, 25, 20000);
mods.forestry.engine.peat.addRecipe(<chisel:block_charcoal2:1>, 15, 20000);
mods.forestry.engine.peat.addRecipe(<forestry:charcoal>, 15, 20000);
mods.forestry.engine.peat.addRecipe(<quark:charcoal_block>, 15, 20000);
